name = "Written Oirat"
version = "0.1.1"

[macos]
system_pkg_id = "no.divvun.MacDivvun.xwo"

[windows]
system_product_code = "{3DB75B39-B3E1-47FA-9C3D-8524351F42F2}_is1"
legacy_product_codes = [
    { value = "C08B9216-1BC0-4757-8B95-36E246685003", kind = "nsis" },
    { value = "B81344CB-EFDF-4882-BD15-E8AC539C2729", kind = "nsis" }
]
