spellername = "Written Oirat"
spellerversion = "0.1.1"

# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Written Oirat spellchecker"
xwo = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Written Oirat, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
xwo = "TRANSLATE: A spellchecker for Written Oirat, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.xwo"

[windows]
system_product_code = "{3DB75B39-B3E1-47FA-9C3D-8524351F42F2}_is1"
legacy_product_codes = [
    { value = "C08B9216-1BC0-4757-8B95-36E246685003", kind = "nsis" },
    { value = "B81344CB-EFDF-4882-BD15-E8AC539C2729", kind = "nsis" }
]
