template = "https://github.com/giellalt/template-lang-und"
rev_id = 303
template_sha = "b019fafa945ec21f8f1ee983a95aba800ec89260"

[replacements]
__GLOTTOLOG_ID__ = "torg1245"
__REPO__ = "lang-xwo"
__UND2C__ = "xwo"
__UNDEFINED__ = "Written Oirat"
__UND__ = "xwo"
