template = "https://github.com/giellalt/template-lang-und"
rev_id = 320
template_sha = "67266bcec9c778bce3d70cc0a78e75bdec65cc66"

[replacements]
__GLOTTOLOG_ID__ = "torg1245"
__REPO__ = "lang-xwo"
__UND2C__ = "xwo"
__UNDEFINED__ = "Written Oirat"
__UND__ = "xwo"
