template = "https://github.com/giellalt/template-lang-und"
rev_id = 296
template_sha = "879b03783ce7c34cc6b4dfc240164614f484a26e"

[replacements]
__GLOTTOLOG_ID__ = "torg1245"
__REPO__ = "lang-xwo"
__UND2C__ = "xwo"
__UNDEFINED__ = "Written Oirat"
__UND__ = "xwo"
