[package]
name = "xwo"
human_name = "Written Oirat"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.xwo]
filename = "xwo-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-xwo"
platform = "windows"
uuid = "C08B9216-1BC0-4757-8B95-36E246685003"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.xwo"
package = "speller-xwo"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-xwo-mso"
platform = "windows"
uuid = "B81344CB-EFDF-4882-BD15-E8AC539C2729"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-xwo"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
